apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: deno-fresh-example-secrets
  namespace: deno-fresh-example
  labels:
    app: frontend
    managed-by: skaffold
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: deno-fresh-example-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        # Environment for production runtime
        NODE_ENV: "production"
        # Site URL for canonical redirects and absolute links
        NEXT_PUBLIC_SITE_URL: "{{ .NEXT_PUBLIC_SITE_URL }}"
        # Stripe (optional for this demo — kept for parity with example)
        STRIPE_SECRET_KEY: "{{ .STRIPE_SECRET_KEY }}"
        STRIPE_PUBLISHABLE_KEY: "{{ .STRIPE_PUBLISHABLE_KEY }}"
        STRIPE_WEBHOOK_SECRET: "{{ .STRIPE_WEBHOOK_SECRET }}"
  data:
    - secretKey: NEXT_PUBLIC_SITE_URL
      remoteRef:
        key: deno-fresh-example-secrets
        property: site_url
    - secretKey: STRIPE_SECRET_KEY
      remoteRef:
        key: deno-fresh-example-secrets
        property: stripe_secret_key
    - secretKey: STRIPE_PUBLISHABLE_KEY
      remoteRef:
        key: deno-fresh-example-secrets
        property: stripe_publishable_key
    - secretKey: STRIPE_WEBHOOK_SECRET
      remoteRef:
        key: deno-fresh-example-secrets
        property: stripe_webhook_secret

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-secret
  namespace: deno-fresh-example
  labels:
    app: frontend
    managed-by: skaffold
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: ghcr-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "ghcr.io": {
                "username": "{{ .GITHUB_USERNAME }}",
                "password": "{{ .GITHUB_TOKEN }}",
                "auth": "{{ printf "%s:%s" .GITHUB_USERNAME .GITHUB_TOKEN | b64enc }}"
              }
            }
          }
  data:
    - secretKey: GITHUB_USERNAME
      remoteRef:
        key: deno-fresh-example-github
        property: username
    - secretKey: GITHUB_TOKEN
      remoteRef:
        key: deno-fresh-example-github
        property: password

