apiVersion: v1
kind: ServiceAccount
metadata:
  name: deno-fresh-example
  namespace: deno-fresh-example
  labels:
    app: frontend

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deno-fresh-example-read
  namespace: deno-fresh-example
rules:
  - apiGroups: [""]
    resources: ["pods", "configmaps", "secrets"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deno-fresh-example-read-binding
  namespace: deno-fresh-example
subjects:
  - kind: ServiceAccount
    name: deno-fresh-example
    namespace: deno-fresh-example
roleRef:
  kind: Role
  name: deno-fresh-example-read
  apiGroup: rbac.authorization.k8s.io

